VQVAE:
  z_channels: 4
  codebook_size : 8192
  down_channels : [64, 128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, True, True, True]
  attn_down : [False, False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

cond_model:
  down_channels: [ 128, 256, 256, 256]
  mid_channels: [ 256, 256]
  down_sample: [ False, False, False ]
  attn_down : [True, True, True]
  time_emb_dim: 256
  norm_channels : 32
  num_heads : 16
  conv_out_channels : 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  im_channels : 3
  condition_config:
    condition_types: [ 'text', 'image' ]
    condition_types: ['image']
    text_condition_config:
      text_embed_model: 'clip'
      train_text_embed_model: False
      text_embed_dim: 256
      cond_drop_prob: 0.1
    image_condition_config:
      image_condition_input_channels: 18
      image_condition_output_channels: 3
      image_condition_h : 256
      image_condition_w : 256
      cond_drop_prob: 0.1

dataset_params:
  name: 'celeb'
  im_path: '/home/dusan/Desktop/ML_PROJECTS/ml_datasets/CelebAMask-HQ'
  im_channels : 3
  im_size : 256
  im_ext: 'jpg'
  split: 'train'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0015
  beta_end : 0.0195

UnetParams:
  down_channels: [ 256, 384, 512, 768 ]
  mid_channels: [ 768, 512 ]
  down_sample: [ True, True, True ]
  attn_down : [True, True, True]
  time_emb_dim: 512
  norm_channels : 32
  num_heads : 16
  conv_out_channels : 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  im_channels : 3

train_params:
  seed : 1111
  task_name: 'celeb_ddpm_cond'
  task_name_ddpm_vqvae: 'celeb_ddpm_vqvae'
  task_name_ddpm_cond: 'celeb_ddpm_vqvae_cond'
  vqvae_model: 'celebhq'
  ldm_batch_size: 32
  ldm_img_save_steps: 300
  autoencoder_batch_size: 8
  disc_start: 1000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  kl_weight: 0.000005
  ldm_epochs : 100
  autoencoder_epochs : 10
  num_samples : 8
  num_grid_rows : 4
  ldm_lr: 0.00001
  autoencoder_lr: 0.0001
  autoencoder_acc_steps : 1
  autoencoder_img_save_steps : 128
  save_latents : False
  vae_latent_dir_name : 'vae_latents'
  vqvae_latent_dir_name : 'vqvae_latents'
  ldm_ckpt_name: 'ddpm_cond_ckpt.pth'
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
